### ISSUE TITLE
Generate the Visibility Map

### ISSUE THREAD

**Issue by WERush** [silverbottlep/tvsn#1]
Hi, Eunbyung,

I want to generate the Visibility Map between the frontal view(input view) and bird-eye view(target view). What should I do to make it happen? Since there is no instruction of ObjRenderer, I do not know how to change the config.txt to meet my needs. Can you help me? Thanks

Best

**Comment by silverbottlep** [comment]
sorry for late response. I didn't get visibility map via ObjRenderer. I got depth and normal from ObjRenderer, and generated visibility map via gen_vis_maps
