### ISSUE TITLE
How get correct nomal from ObjRenderer

### ISSUE THREAD

**Issue by Mykheievskyi** [silverbottlep/tvsn#4]
Hi, Eunbyung,

I start rendering dataset, everything goes well renders the image and coordinates but returns zero normals. And I can't count visible maps. Can you help me? Thanks

**Comment by EdwardSmith1884** [comment]
I have the same problem, it appears, that the line, [here](https://github.com/silverbottlep/ObjRenderer/blob/458e8f1f57d8da34a869308b38818372b6c7fb70/genViewsShapenet.h#L119), does not properly set normals to be produced, as the output of following line,  [here](https://github.com/silverbottlep/ObjRenderer/blob/458e8f1f57d8da34a869308b38818372b6c7fb70/genViewsShapenet.h#L120),  is always an image of zeros. Do you have any info on how to solve this?

**Comment by EdwardSmith1884** [comment]
From the looks of it, by setting  [here](https://github.com/silverbottlep/ObjRenderer/blob/458e8f1f57d8da34a869308b38818372b6c7fb70/genViewsShapenet.h#L119) to be 4, this calls the switch [here](https://github.com/silverbottlep/ObjRenderer/blob/458e8f1f57d8da34a869308b38818372b6c7fb70/Shader/main.frag#L11) which has no 4th case and so zeros are returned. I have tried allowing the [shadeNorm()]( https://github.com/silverbottlep/ObjRenderer/blob/458e8f1f57d8da34a869308b38818372b6c7fb70/Shader/norm.frag#L4 ) function to be called with the 4th case, but the outputs from this function still do not seem to be the correct normals. I think the function for accessing normals might not implemented properly here.

**Comment by silverbottlep** [comment]
@Mykheievskyi @EdwardSmith1884 sorry, not sure what went wrong at this point, it should be just small mistake, hopefully I can have time to take a look. In the mean time, you can download rendered images [here](https://drive.google.com/drive/folders/0B-r7apOz1BHAWXYwT1lGb3J1Yjg?usp=sharing), and you can download visibility maps [maps_chair.t7](https://drive.google.com/open?id=0B-r7apOz1BHANGlsY1k3Z29yVEU) and [maps_chair.t7](https://drive.google.com/open?id=0B-r7apOz1BHANGlsY1k3Z29yVEU).

**Comment by Mykheievskyi** [comment]
@silverbottlep  @EdwardSmith1884 I solved this problem, you foget implement [shadeNorm()](https://github.com/silverbottlep/ObjRenderer/blob/master/Shader/norm.frag) vector in [main()](https://github.com/silverbottlep/ObjRenderer/blob/master/Shader/main.frag#L13):
`#version 330

uniform uint outputID;

out vec4 color;

vec4 shadePhong();
vec4 shadeCoord();
vec4 shadeBRDF();
vec4 shadeNorm();

void main()
{
    switch(outputID)
    {
	case 1u:
        color = shadeCoord();
		return;
	case 2u:
		color = shadePhong();
		return;
	case 3u:
		color = shadeBRDF();
		return;
        case 4u:
                color = shareNorm();
                return;
    }
}`

**Comment by Mykheievskyi** [comment]
@silverbottlep  @EdwardSmith1884 I solved this problem, you forgot implement  [shadeNorm()](https://github.com/silverbottlep/ObjRenderer/blob/master/Shader/norm.frag) vector in [main()](https://github.com/silverbottlep/ObjRenderer/blob/master/Shader/main.frag#L13):
```
#version 330

uniform uint outputID;

out vec4 color;

vec4 shadePhong();
vec4 shadeCoord();
vec4 shadeBRDF();
vec4 shadeNorm();

void main()
{
    switch(outputID)
    {
	case 1u:
        color = shadeCoord();
		return;
	case 2u:
		color = shadePhong();
		return;
	case 3u:
		color = shadeBRDF();
		return;
        case 4u:
                color = shareNorm();
                return;
    }
}
```

**Comment by EdwardSmith1884** [comment]
@Mykheievskyi thanks for the help, this is also what I tried, but I didn't visualise the normals right and so was confused. Just to confirm, was this enough to produce the correct visibility maps on your end?

**Comment by Mykheievskyi** [comment]
@EdwardSmith1884 this will give you the normal vectors for every rotation step. To get a visible map you need use matlab [script](https://github.com/silverbottlep/tvsn/blob/master/gen_vis_maps/gen_vis_maps.sh#L8).

**Comment by silverbottlep** [comment]
@Mykheievskyi @EdwardSmith1884 thanks guys! I fixed this on the ObjRenderer repository.
